# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff4ffd7602371713183daae82cbb578e0f178da026f3d95d1f0424463556fcacf70c83fb89ae3c4fc613f720dc7339ddd9d79c79c8ddb5535bfe332aa55a31a2

test:
  secret_key_base: 8a900475cb1ea1f23857fbc5c937fd1124e69ae579444a296bdc2752133700a9bcdc3ecd5cc89ad778d6d6f1eb81b74d613c15280088419e8b92d2e203b7f17a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
